config/routes.rb
# require 'sidekiq/web'
Rails.application.routes.draw do

  namespace "api" do 
    namespace "v1" do 
       devise_for :users, default: {format: :json } , controllers: {
        sessions: 'api/v1/users/sessions' , registrations: 'api/v1/users/registrations' }
        namespace :users do 

        resource :profile , :only => [:show]
        end
        resources :products do 
          collection do 
            post :login 
          end 
        end 
        resources :cart_items
        resources :home 
        resources :order_items
        resources :variants
        
        resources :addresses do
          collection do
            get :select_address
          end
          
        end



    end
  end 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   # mount Sidekiq::Web => '/sidekiq'

  devise_for :users, :path => "users", controllers: {
        sessions: 'users/sessions'}

  resources :users do
    resources :addresses do
      collection do
        get :select_address
      end
    end
  end
# mount Sidekiq::Web => '/sidekiq'
root to: "products#index"  
resources :products 
resources :carts
resources :variants
resources :cart_items
resources :order_items
resources :payments
resources :home

# resources :addresses do
#   collection do
#     get :select_address
#   end
  
# end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :variant
  #   def self.ransackable_attributes(auth_object = nil)
  #   ["cart_id", "created_at", "id", "quantity", "save_for_later", "updated_at", "variant_id"]
  # end

end

app/controllers/api/v1/cart_items_controller.rb
class Api::V1::CartItemsController < ApplicationController
 

	def index
		current_user = User.find(params[:id])
		@cart = current_user.cart #since has_one association
		@cart_items =@cart.cart_items
		render json: @cart_items , status: 200 
		
	end 


	def create
		current_user = User.find(params[:id])
		@cart = current_user.cart

			
			if @item =CartItem.find_by(variant_id: form_params[:variant_id])
				@item.update(quantity: (@item.quantity + 1))
				render json: @cart , status: 200

			else 
				@cart_item = @cart.cart_items.new(form_params)
				@cart_item.save
				render json: @cart , status: 200
			end
		
	end 

	def update 

		@cartitem = CartItem.find(params[:id])

		if params[:decrease]
			@cartitem.update(quantity: (@cartitem.quantity - 1))
			 

		elsif params[:increase]
			@cartitem.update(quantity: (@cartitem.quantity + 1))
			
	
		
		elsif params[:save_for_later] 
			@cartitem.update(save_for_later: true)
			
		
		elsif params[:move_to_cart]
			@cartitem.update(save_for_later: false)
			
			

		elsif params[:remove_from_list]
			@cartitem.destroy
			
	

		elsif params[:proceed_to_checkout]
			redirect_to  default_address_address_path
		end 

		render json: @cartitem , status: 200
	
	end

	
	private
    def form_params
    	params.require(:cart_item).permit(:variant_id , :quantity)
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
 

	def index
	
		@cart = current_user.cart #since has_one association
		@cart_items =@cart.cart_items
		
	end 


	def create
		
		@cart = @current_user.cart
			
			if @item =CartItem.find_by(variant_id: form_params[:variant_id])
				@item.update(quantity: (@item.quantity + 1))


			else 
				@cart_item = @cart.cart_items.new(form_params)
				@cart_item.save
			end

			render json: @cart , status: 200

		
	end 

	def update 
		@cartitem = CartItem.find(params[:id])

		debugger
		if params[:decrease]

			@cartitem.update(quantity: (@cartitem.quantity - 1))
			redirect_to cart_items_path

		elsif params[:increase]
			@cartitem.update(quantity: (@cartitem.quantity + 1))
			redirect_to cart_items_path
	
		
		elsif params[:save_for_later]
			@cartitem.update(save_for_later: true)
			redirect_to cart_items_path
		
		elsif params[:move_to_cart]
			@cartitem.update(save_for_later: false)
			redirect_to cart_items_path
			

		elsif params[:remove_from_list]
			@cartitem.destroy
			redirect_to cart_items_path 
	

		elsif params[:proceed_to_checkout]
			redirect_to  default_address_address_path
		end 

		render json: @cartitem , status: 200
	
	end

	
	private
    def form_params
    
    	params.require(:cart_item).permit(:variant_id , :quantity)
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper

def cart	
cartvalue=0
end

def save_for_later_f(a)
	if a.where(save_for_later: false).count >0
		return true

	else
		return false
	end
end

def save_for_later_t(a)
	if a.where(save_for_later: true).count >0
		return true

	else
		return false
	end
end


def display_image(a)
	Rails.application.routes.url_helpers.rails_blob_url(a.images.first, only_path: true)
end



def check_for_f(a)
	if a.save_for_later == false
		return true
	
	else
		return false
	end
end


def check_for_t(a)
	if a.save_for_later == true
		return true
	
	else
		return false
	end
end


def value(a , b, c)
   a+(price(b)*quantity(c))
end


def price(a)
	a.price
end

def colour(a)
	a.colour
end

def material(a)
	a.material
end

def weight(a)
	a.weight
end

def quantity(a)
    a.quantity.to_i
end

def product(a)
	a.product
end

def check(a)
	if quantity(a)>1
		return false
	else
		return true
	end
end
end

app/views/cart_items/index.html.erb
<div class="temp">
	<div class="overall" >
		<div class="main">
			<h1> Your cart</h1>
			<%cartvalue=0%>
			<%if save_for_later_f(@cart_items)%>
				<%@cart_items.each do |cartitem|%>

					<% variant =cartitem.variant%> 

					<%if check_for_f(cartitem)%>               
					                         &nbsp&nbsp&nbsp&nbsp
						<%product=variant.product%> 
						<div class="product_cart">
								<div class="image">
									<%=image_tag  display_image(variant), size: "210x210" ,:style => "object-fit: contain "%>
								</div>

							<div class="product_details">			
								<h2><%=product.name%> <%=product.brand_name %></h2>        				
								<h3 class="item_price">Rs.<%=price(variant)%></h3>	
								<h4>Colour: <%= colour(variant)%> &nbsp&nbsp&nbsp&nbsp Material: <%= material(variant)%>&nbsp&nbsp&nbsp&nbsp weight: <%= weight(variant)%></h4>
												
								<%cartvalue= value(cartvalue,variant,cartitem)%>
													

									<%=form_with  model:cartitem , method: :patch do |form|%>						<%=form.submit "-", name: "decrease", :disabled => check(cartitem)%>
										<%=form.number_field :quantity ,disabled: true ,:value => quantity(cartitem) , :style => "font-size: 15px; width: 18%; padding-left:20px; "%>
										<%=form.submit "+", name: "increase"%>
										<h4><%=form.submit "Save for later", name: "save_for_later"%></h4>
									<%end%>

							</div>	



						</div>	
					<%end%>
				<%end%>

			<%else%>
				<h2 align="center">Your cart is empty ! :(</h2>
			<%end%>	
			<div class="save_later">
			<%if save_for_later_t(@cart_items)%>
			<h1>Save for later</h1>
			<%end%>


			<%@cart_items.each do |cart_item|%>
			<%if check_for_t(cart_item)%>




			<% variant =cart_item.variant%> 
			<%product=product(variant)%>  

			<div class="save_later_main">
			<div class="image">
							<%=image_tag  display_image(variant), size: "210x210" ,:style => "object-fit: contain "%>
						</div>
						<div class="save_for_later_details">

						<h2><%=product.name%></h2>         				
						<h3>RS. <%=variant.price%></h3>					
						<h4>Colour: <%= colour(variant)%> &nbsp&nbsp&nbsp&nbsp Material: <%= material(variant)%>&nbsp&nbsp&nbsp&nbsp weight: <%= weight(variant)%></h4>
											


					<%=form_with  model:cart_item , method: :patch do |form|%>
					
					    <h4><%=form.submit "Remove form list ", name: "remove_from_list"%> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
						<%=form.submit "Move to cart", name: "move_to_cart"%></h4>
					
					
					<%end%>
					</div>	
				</div>		

			<%end%>
			<%end%>



			</div>



		</div>


	</div>
		<div class="user_cart_value">
			<div class="proceed">
				<h1>Your cart value</h1>
				<h2>Number of items : <%= @cart_items.where(save_for_later: false).count%></h2>
				<h2>Total amount:  <%= cartvalue%> </h2>
			</div>
		<h3><button class="proceed_btn"><%=link_to "Proceed to check out" ,  select_address_addresses_path%></button></h3>
		</div>
</div>


<style type="text/css">
	.overall{

	}

	.user_value{

	}
	.product_details{
		margin-top: -3vh;
		margin-left: 150px;
	}
	.item_price{
		color: red;
	}
	.product_cart{
		display: flex;
		margin-bottom: 50px;

	}
	.main{
		margin-top: 100px;
		margin-left: 70px;
	}
	.user_cart_value
	{
	  margin-top: 100px;
	}

	.user_cart_value h2 {
		margin-top: 30px;
		margin-left: 20px;
	}

	.user_cart_value h1 {
		
		
	}
	.save_later{

	}
	.save_later_main{
		display: flex;
		margin-top: 50px;
	}

	.save_for_later_details{
		margin-left: 150px;
	}
	.temp {
		display: flex;
    flex-direction: row;
        justify-content: space-around;
	}

	.proceed{
		
		background-color: #ebf0f9;;
		border-radius: 15px;
		padding: 8px 45px 45px 45px;
	}
	.proceed_btn{
		color: red;
		padding: 20px;
		margin-left: 70px;
	}
</style>

app/views/cart_items/temp.html.erb
<h1> Your cart</h1>
<%cartvalue=0%>
<%@cart_items.each do |cartitem|%>
<table>
<% @variant =cartitem.variant%> 
	<tr>
	<%if cartitem.save_for_later == false%>               
			                             &nbsp&nbsp&nbsp&nbsp
			<%@product=@variant.product%>   		
			<td><%=@product.name%></td>         				
			<td><%=@variant.price%></td>					
			<td><%=cartitem.quantity%></td>
			<%cartvalue= cartvalue+(@variant.price*cartitem.quantity)%>
									
		
		<%=form_with  model:cartitem , method: :patch do |form|%>
		<td><%=form.submit "-", name: "decrease"%>
		<%=form.number_field :quantity ,disabled: true , :value => cartitem.quantity%>
		<%=form.submit "+", name: "increase"%>
			<%=form.submit "Save for later", name: "save_for_later"%>
		</td>
		<%end%>
		
		
	<%else%>
	<%end%>
	</tr>
</table>

<%end%>
<h3 align="center">Your cart vale: <%= cartvalue%></h3>


<h1>Save for later</h1>

<table>
<%@cart_items.each do |cart_item|%>
<%if cart_item.save_for_later == true%>

<tr>
<% @variant =cart_item.variant%> 
<%@product=@variant.product%>   		
			<td><%=@product.name%></td>         				
			<td><%=@variant.price%></td>					
			


		<%=form_with  model:cart_item , method: :patch do |form|%>
		<td>
		    <%=form.submit "Remove form list ", name: "remove_from_list"%>
			<%=form.submit "Move to cart", name: "move_to_cart"%>
		</td>
		<%end%>
			
			
<%else %>	
<%end%>
<%end%>
</tr>
</table>

<button><%=link_to "Proceed to check out" ,  select_address_addresses_path%></button>