config/routes.rb
# require 'sidekiq/web'
Rails.application.routes.draw do

  namespace "api" do 
    namespace "v1" do 
       devise_for :users, default: {format: :json } , controllers: {
        sessions: 'api/v1/users/sessions' , registrations: 'api/v1/users/registrations' }
        namespace :users do 

        resource :profile , :only => [:show]
        end
        resources :products do 
          collection do 
            post :login 
          end 
        end 
        resources :cart_items
        resources :home 
        resources :order_items
        resources :variants
        
        resources :addresses do
          collection do
            get :select_address
          end
          
        end



    end
  end 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   # mount Sidekiq::Web => '/sidekiq'

  devise_for :users, :path => "users", controllers: {
        sessions: 'users/sessions'}

  resources :users do
    resources :addresses do
      collection do
        get :select_address
      end
    end
  end
# mount Sidekiq::Web => '/sidekiq'
root to: "products#index"  
resources :products 
resources :carts
resources :variants
resources :cart_items
resources :order_items
resources :payments
resources :home

# resources :addresses do
#   collection do
#     get :select_address
#   end
  
# end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController	
	include Separable
   
	def index 
		user = User.find(params["user_id"])
		@addresses = user.addresses
	end
	
	# def all_address
	# 	@addresses = Address.where(user_id:current_user[:id])
	# end

	def select_address
		 @address=current_user.addresses.find_by(default_address: true)
		 @select_address = current_user.addresses.where(default_address: false)
		 
		 	if params[:proceed]
		 		redirect_to new_order_item_path
		 	end
		
	end 

	def show
	  	find_address
	end

	def edit
		find_address
		@cities= City.pluck(:name , :id)
			
	end

	def update
		binding.pry

		@address  = find_address
		user = User.find(params["user_id"])
		
			if params[:def_address]
				@user_addresses = Address.where(user_id: user.id)
				puts @user_addresses
				binding.pry

				@user_addresses.each do |e|
					e.update(default_address: "false")
				end

				find_address
				@address.update(default_address: "true") 
				render :show,status: 200
				# redirect_to address_path

			
			elsif params[:select_for_delivery]

				@user_addresses = Address.where(user_id: user.id)
				@user_addresses.each do |e|
					e.update(default_address: "false")
				end

				@def_address =Address.find(params[:id])
				@def_address.update(default_address: true)
				# redirect_to select_address_addresses_path 
				 render :show ,status: 200


			elsif params[:proceed]
		 		redirect_to new_order_item_path
		 
		

			elsif params[:edit_address]
				redirect_to edit_address_path

			elsif params[:remove_address]
				binding.pry
				@address.destroy
				# redirect_to select_address_addresses_path
				render :show , status: 200

			elsif @address.update(address_param)
				redirect_to address_path



			else
				render "/edit"
			end

	end


	def new 
		@cities= City.pluck(:name , :id)
		puts @cities
		@address = Address.new 
	end

	def create 
		binding.pry
		user = User.find(params["user_id"])
		@address = user.addresses.new(address_param)

		if @address.save
			# redirect_to root_path
			render :show , status: :created
		else
			render :new
		end
	end



private 
	def address_param
		binding.pry
		params.require(:address).permit(:address_line_1, :address_line_2, :house_room_number, :landmark,:pin_code , :city_id)
	end

	

end
 

app/controllers/api/v1/addresses_controller.rb
class Api::V1::AddressesController < ApplicationController
	
	# load_and_authorize_resource
	# skip_befor_action :verify_authenticity_token

   
	def index 
		user = User.find(params[:user_id])
		@addresses = user.addresses
		render json: @addresses , status: 200
	end
	
	# def all_address
	# 	@addresses = Address.where(user_id:current_user[:id])
	# end

	def select_address

		
		current_user = User.find(params[:id])
		 @address=current_user.addresses.find_by(default_address: true)
		 @select_address = current_user.addresses.where(default_address: false)
		 
		 	if params[:proceed]
		 		
    @user = User.find(params[:id])
    # @user.update()
    render json: {user: @user , address: @address , select_address: @select_address } , status: 200
  # redirect_to new_order_item_path
		 	end
		
	end 

	def show
	  	 @address = Address.find_by(id: params[:id])
	  	 render json: @address , status: 200
	end

	def edit
		 @address = Address.find_by(id: params[:id])
		@cities= City.pluck(:name , :id)
		render json: { address: @address , cities: @cities} ,staus: 200
			
	end

	def update
		 @address = Address.find_by(id: params[:id])
		
			if params[:def_address]
				@user_addresses = Address.where(user_id: current_user.id)
				puts @user_addresses
				# binding.pry

				@user_addresses.each do |e|
					e.update(default_address: "false")
				end

				 @address = Address.find_by(id: params[:id])
				@address.update(default_address: "true") 
				redirect_to address_path

			
			elsif params[:select_for_delivery]
				@user_addresses = Address.where(user_id: current_user.id)
				@user_addresses.each do |e|
					e.update(default_address: "false")
				end

				@def_address =Address.find(params[:id])
				@def_address.update(default_address: true)
				redirect_to select_address_addresses_path


			elsif params[:proceed]
		 		redirect_to new_order_item_path
		 
		

			elsif params[:edit_address]
				redirect_to edit_address_path

			elsif params[:remove_address]
				binding.pry
				@address.destroy
				redirect_to select_address_addresses_path

			elsif @address.update(address_param)
				redirect_to address_path



			else
				render "/edit"
			end



	end


	def new 
		@cities= City.pluck(:name , :id)
		puts @cities
		@address = Address.new 

		render json: @cities , status: 200
	end

	def create 
		current_user = User.find(params[:id])
		@address = current_user.addresses.new(address_param)
		if @address.save
			# redirect_to root_path
			render json: @address, status: 201 
		else
			render "/new"
		end
	end



private 
	def address_param
		params.require(:address).permit(:address_line_1, :address_line_2, :house_room_number, :landmark,:pin_code , :city_id)
	end

	

end
 

app/helpers/address_helper.rb
module AddressHelper

	def address_1(a)
		a.address_line_1
	end
	def address_2(a)
		a.address_line_2
	end
	def house_no(a)
		a.house_room_number
	end
	def landmark(a)
		a.landmark
	end
	def pin(a)
		a.pin_code
	end


	
end

app/views/addresses/edit.html.erb
<%=form_for [current_user,@address] do |form|%>
<h1>Edit address</h1>
   <ul>
        <li>    
                <%= form.label :address_line_1 %><br>
                <%= form.text_field :address_line_1 %>
        </li>
        <li>    
                <%= form.label :address_line_2 %><br>
                <%= form.text_field :address_line_2 %>
        </li>
        <li>    
                <%= form.label :house_number %><br>
                <%= form.text_field :house_room_number %>
        </li>
        <li>    
                <%= form.label :landmark %><br>
                <%= form.text_field :landmark %>
        </li>
        <li>    
                <%= form.label :pin_code %><br>
                <%= form.text_field :pin_code %>
        </li>

        <li>    
                <%= form.label :city %><br>
                <%= form.select :city_id ,@cities%>
        </li>

   </ul>

    <%= form.submit "submit"%>
    <%= form.submit "set Default Address" , name: "def_address"%>

    <%end%>

app/views/addresses/index.html.erb
<div class="b">

<%=link_to "Add address" , new_user_address_path(current_user.id) %>
<% @addresses.each do |e|%>
<br><%=link_to e.address_line_1 , user_address_path(current_user,e.id)%>
<%end%>

<h3><%=link_to "show products", products_path%></h3>
<%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete
      ) %>


<h3><%= link_to "My_orders", order_items_path %></h3>
</div>

<style type="text/css">
        
.b{
        margin-top: 100px;
        border: 5px red solid;
        background: black;
        color: white;
}
</style>

app/views/addresses/new.html.erb
<h1>Add Address</h1>
<%= form_for [current_user,current_user.addresses.build]  do |form|%>

   <ul>
        <li>    
                <%= form.label :address_line_1 %><br>
                <%= form.text_field :address_line_1 %>
        </li>
        <li>    
                <%= form.label :address_line_2 %><br>
                <%= form.text_field :address_line_2 %>
        </li>
        <li>    
                <%= form.label :house_number %><br>
                <%= form.text_field :house_room_number %>
        </li>
        <li>    
                <%= form.label :landmark %><br>
                <%= form.text_field :landmark %>
        </li>
        <li>    
                <%= form.label :pin_code %><br>
                <%= form.text_field :pin_code %>
        </li>

        <li>    
                <%= form.label :city %><br>
                <%= form.select :city_id ,@cities%>
        </li>

   </ul>

    <%= form.submit "submit"%>

    <%end%>

app/views/addresses/select_address.html.erb
<div class="main">
    <div class="current_address">
		<h1>Delivery Address</h1>
		<div class="text">
			<h3 class="heading">Address1: <%=address_1(@address)%> &nbsp&nbsp Address2: <%=address_2(@address)%></h3>
			<h3>House/Room No. : <%=house_no(@address)%> &nbsp&nbsp Landmark: <%=landmark(@address)%> &nbsp&nbsp Pin code: <%=pin(@address)%> </h3>
		</div>
		<%=form_with model:@address, method: :patch do |form|%>
		<%=form.submit "Proceed for payment", name: "proceed" , :style =>" padding-top:95px; padding-bottom:95px; padding-left:70px; padding-right:70px; border-radius:130px; display:flex; margin-top:-188px; margin-left:849px; z-index:2; font-size:25px;color: white; font-weight:500; "%>
		<%end%>
	</div>
	<div class="select_address">
		<h1>Change address</h1>
		<div class="select_address_text">
			<h2 class="head">Available addresses:</h2>
			<%@select_address.each do |e|%>
			<div class="entity">

				<h3>Address1: <%=address_1(e)%> &nbsp&nbsp Address2: <%=address_2(e)%></h3>
				<h3>House/Room No. : <%=house_no(e)%> &nbsp&nbsp Landmark: <%=landmark(e)%> &nbsp&nbsp Pin code: <%=pin(e)%> </h3>
				<%=form_with model: e ,method: :patch do |form| %>
					<%=form.submit "select for delivery",  name: "select_for_delivery" ,:style =>"background:#2f97ffe3; padding:12px; border:0px; color:black; font-weight:500; font-size:16px; box-shadow: 0px 0px 30px 1px #1f8fff; margin-top:10px;"%>

					<%=form.submit "edit address", name: "edit_address" ,:style =>"background:#2f97ffe3; padding:12px; margin-left:50px; border:0px; color:black; font-weight:200; font-size:16px; box-shadow: 0px 0px 30px 1px #1f8fff; margin-top:10px;"%>

					<%=form.submit "remove address", name: "remove_address" ,:style =>"background:#2f97ffe3; padding:12px; margin-left:50px; border:0px; color:black; font-weight:200; font-size:16px; box-shadow: 0px 0px 30px 1px #1f8fff; margin-top:10px;"%>
				<%end%>
			</div>
			<%end%>
		</div>
	</div>

	<div class="add_button">
		<a href="/addresses/new"><button class="button">Add new address +</button></a>
	</div>
</div>


<style type="text/css">
	.current_address{
		
		background: #2f97ffe3;
		border: 5px #2f97ffe3 solid;
	    padding-left: 120px;
	    border-radius: 150px;
	    margin-right: 261px;
	    padding-bottom: 0px;
	    padding-top: 15px;
	    margin-top: 120px;
	    box-shadow: 0px 0px 40px 1px #437fd9;

		}

	.current_address h3 {
		color: white;
		font-size: 18px;
	}
	.current_address h1{
		color: #4e5778fc;
	}
	.main {
	
		margin-left: 230px;
	}
	.select_address{
		margin-top: 60px;
		border: 5px #2f97ff8a solid;
		padding-left: 100px;
		padding-top: 25px;
		padding-bottom: 20px;
		border-radius: 100px;
		margin-right: 800px;
		background: white;
/*		box-shadow: 0px 0px 30px 1px #1f8fff;*/
	}

	.select_address_text{
		padding-top: 15px;
	}
	.heading{
		padding-top: 15px;
	}
	.text{
		padding-left: 50px;
		padding-bottom: 10px;
	}
	.entity{
		padding-bottom: 35px;
		padding-left: 50px;
	}
	.head{
		padding-left: 20px;
		padding-bottom: 20px;
	}
	.add_button{
		display: flex;	
	    margin-right: 15vw;
	    display: flex;
	    flex-direction: row-reverse;
	    margin-top: -50vh;
	}
	.button{
		
		background: #fb641b;
	    padding-left: 100px;
	    padding-right: 100px;
	    padding-bottom: 50px;
	    padding-top: 50px;
	    font-size: 28px;
	    font-weight: 400;
	    box-shadow: 0px 0px 40px 1px #fb641b;
	    border: 0px;
	}
	.button:hover{
		background: #fb641b;
	}

</style>

app/views/addresses/show.html.erb
<div class="main"> 
<%= @address.address_line_1%><br>

<%= @address.address_line_2%><br>
<%= @address.house_room_number%><br>

<%= @address.address_line_1%><br>
<%=link_to "edit address", edit_user_address_path(current_user,@address) %>
</div>

<style type="text/css">
	.main{
		background: black;
		margin-top: 100px;
		color: white;
	}
</style>