config/routes.rb
# require 'sidekiq/web'
Rails.application.routes.draw do

  namespace "api" do 
    namespace "v1" do 
       devise_for :users, default: {format: :json } , controllers: {
        sessions: 'api/v1/users/sessions' , registrations: 'api/v1/users/registrations' }
        namespace :users do 

        resource :profile , :only => [:show]
        end
        resources :products do 
          collection do 
            post :login 
          end 
        end 
        resources :cart_items
        resources :home 
        resources :order_items
        resources :variants
        
        resources :addresses do
          collection do
            get :select_address
          end
          
        end



    end
  end 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   # mount Sidekiq::Web => '/sidekiq'

  devise_for :users, :path => "users", controllers: {
        sessions: 'users/sessions'}

  resources :users do
    resources :addresses do
      collection do
        get :select_address
      end
    end
  end
# mount Sidekiq::Web => '/sidekiq'
root to: "products#index"  
resources :products 
resources :carts
resources :variants
resources :cart_items
resources :order_items
resources :payments
resources :home

# resources :addresses do
#   collection do
#     get :select_address
#   end
  
# end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :orders
  validates :pin_code, presence: true , length: {maximum: 6}  

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
         def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end
  

app/models/cart.rb
class Cart < ApplicationRecord
  # belongs_to :variant
  belongs_to :user
  has_many :cart_items
  # belongs_to :address
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :variant
  #   def self.ransackable_attributes(auth_object = nil)
  #   ["cart_id", "created_at", "id", "quantity", "save_for_later", "updated_at", "variant_id"]
  # end

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

#   def self.ransackable_attributes(auth_object = nil)
#     ["created_at", "id", "name", "updated_at"]
#   end
# def self.ransackable_associations(auth_object = nil)
#     ["products", "roles"]
#   end

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state, class_name: "State"
  has_many :address
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :states
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :address
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :variant
  # def self.ransackable_attributes(auth_object = nil)
  #   ["created_at", "id", "order_id", "price", "quantity", "updated_at", "variant_id"]
  # end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :variants
  belongs_to :category

  # def self.ransackable_attributes(auth_object = nil)
  #   ["brand_name", "category_id", "created_at", "description", "id", "name", "updated_at"]
  # end
  # # def self.ransackable_associations(auth_object = nil)
  # #   ["category", "roles"]
  # # end
  #  def self.ransackable_associations(auth_object = nil)
  #   ["category", "roles", "variants"]
  # end


end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
  #     def self.ransackable_attributes(auth_object = nil)
  #   ["created_at", "id", "name", "resource_id", "resource_type", "updated_at"]
  # end
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities, class_name: "City"
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses
  has_many :orders
  has_one :cart

  after_create :create_cart  #filter

  def create_cart
    Cart.create!(user_id: self.id)  
  end
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many_attached :images, dependent: :destroy


 #  def self.ransackable_attributes(auth_object = nil)
 #    ["colour", "created_at", "id", "material","price", "product_id", "updated_at", "weight"]
 #  end
 #  #  def self.ransackable_associations(auth_object = nil)
 #  #   ["cart_items", "order_items", "product", "roles"]
 #  # end
 # def self.ransackable_associations(auth_object = nil)
 #    ["cart_items", "images_attachments", "images_blobs", "order_items", "product", "roles"]
 #  end

end

app/helpers/address_helper.rb
module AddressHelper

	def address_1(a)
		a.address_line_1
	end
	def address_2(a)
		a.address_line_2
	end
	def house_no(a)
		a.house_room_number
	end
	def landmark(a)
		a.landmark
	end
	def pin(a)
		a.pin_code
	end


	
end

app/helpers/authorization.rb
module Authorization
  def initialize(request)
    @token = request.headers[:HTTP_TOKEN]
  end
  def current_user
    token = JsonWebToken.decode(@token)[:email] if @token
    user = User.find_by(email: token["email"])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def display(a)
      Rails.application.routes.url_helpers.rails_blob_url(a.variants.first.images.last, only_path: true)
	end

	def price_p(a)
       a.variants.first.price
	end

	def name(a)
		a.name
	end

	def brand_name(a)
		a.brand_name
	end
end

app/helpers/payments_helper.rb
module PaymentsHelper
	def order
		OrderItem.where(order_id: Order.last.id).sum("price")
	end

	def url
	return "/payments/#{Order.last.id}"
	end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
  </head>

  <body>

      <div class = "background">       
      <div class="topnav" id="myTopnav">
        <b> <%= image_tag "carts.png" ,size: "36x33"%> </b> 
        <p><a class="active" href="/" >Home</a></p>
        
        <div class="dropdown">
         <a class="dropbtn">Category</a>
         <div class="dropdown-content">
           <%Category.all.each do |e|%>
                <a ><%=link_to e.name , home_path(e.id) %></a>
                   
             <%end%>
         </div>

        </div>


        <a href="/order_items">My Orders</a>
        <a href="#about">About</a>
        
          <%if current_user == nil %>
            <%a = "user" %>
          <%else%>
            <%a = current_user[:first_name] %>
          <%end%>
        
      <div class="log" style=" margin-left: auto;">
        <a href="" class="dropbtn"  >hello <%=a%></a>
      <div class="log-content" >
        
        <a><%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete
      ) %></a>
        
      </div>
      </div>





        <div class="cart">
            <a class="cart-icon" href="/cart_items"><i class="fa fa-shopping-cart"><span class="ribbon"><%= CartItem.where(save_for_later: false).count%></span></i></a>
        </div>
      </div>
    </div>

    <%= yield %>
  </body>
</html>